import type { Metadata } from 'next'

import { Header } from '@/components/header/Header'
import { Home } from '@/components/home/Home'
import { CreateTopicModal } from '@/components/modals/CreateTopicModal'
import { UpdateTopicModal } from '@/components/modals/UpdateTopicModal'
import '../globals.css'

export const metadata: Metadata = {
	title: 'Norr',
	description: 'Generated by create next app'
}

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<div className='flex min-h-screen'>
			<Home />
			<div className='flex-1 flex flex-col'>
				<Header />
				<main className='flex-1 p-4'>{children}</main>
			</div>
			<CreateTopicModal />
			<UpdateTopicModal />
		</div>
	)
}
